# Generated by Django 5.1.4 on 2024-12-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
