# Generated by Django 5.1.4 on 2024-12-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ending_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='starting_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
